---
- name: Add DNS entries to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }} {{ item.name }}"
    insertafter: EOF
    state: present
  with_items: "{{ dns_entries }}" 
  become: true
