---
- name: Copy socketio client file 
  copy:
    src: /home/may/Documents/work/project/ansible_project/Poetry_Ansible/roles/socketio/files/pt-agent.tar
    dest: /home/frontiir/pt-agent.tar

- name: Extract socketio client file
  unarchive:
    src: /home/frontiir/pt-agent.tar
    dest: /home/frontiir/
    remote_src: yes

- name: Set Permissions
  file:
    path: "/home/frontiir/pt-agent"
    mode: "777"

- name: Set owner and group
  file:
    path: "/home/frontiir/pt-agent"
    owner: frontiir
    group: frontiir

- name: Remove zip file
  file:
    path: /home/frontiir/pt-agent.tar
    state: absent

- name: Remove .venv 
  file:
    path: /home/frontiir/pt-agent/.venv
    state: absent



